version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5432:5432"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: certification_info
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro